# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/gosimple/unidecode
%global goipath         github.com/gosimple/unidecode
Version:                1.0.1

%gometa -L -f

%global common_description %{expand:
Unicode transliterator in Golang - Replaces non-ASCII characters with their
ASCII approximations.}

%global golicenses      LICENSE
%global godocs          README.md table.txt

Name:           golang-github-gosimple-unidecode
Release:        %autorelease
Summary:        Unicode transliterator in Golang

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
